// Comprehensive demo data showcasing agentic functionality, AI grading, Exa search, gamification

export const DEMO_USER_ID = "demo-user-00000000-0000-0000-0000-000000000001";

// ── Gamification Progress ──
export const demoProgress = {
  id: "prog-001",
  user_id: DEMO_USER_ID,
  xp: 680,
  level: 7,
  streak_days: 5,
  momentum_score: 62,
  last_activity_at: new Date(Date.now() - 2 * 3600000).toISOString(),
  created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  updated_at: new Date().toISOString(),
};

// ── Courses ──
const COURSES = {
  cs101: { id: "course-cs101", title: "CS101: Intro to Programming", subject: "Computer Science", teacher_id: "teacher-001" },
  cs201: { id: "course-cs201", title: "CS201: Data Structures & Algorithms", subject: "Computer Science", teacher_id: "teacher-001" },
  ai301: { id: "course-ai301", title: "AI301: Intro to Artificial Intelligence", subject: "AI & ML", teacher_id: "teacher-002" },
};

// ── Assignments (5 types) ──
export const demoAssignments = [
  {
    id: "asgn-001",
    title: "Python Data Types Quiz",
    description: "Test your understanding of Python's built-in data types including strings, lists, tuples, dictionaries, and sets. Answer all questions.",
    type: "mcq",
    course_id: COURSES.cs101.id,
    courses: { title: COURSES.cs101.title },
    max_score: 100,
    is_mandatory: true,
    due_date: new Date(Date.now() - 2 * 86400000).toISOString(),
    answer_key: { options: ["list", "tuple", "set", "dictionary"], correct: "tuple" },
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
  {
    id: "asgn-002",
    title: "Explain Object-Oriented Programming",
    description: "Write a detailed essay explaining OOP principles: encapsulation, inheritance, polymorphism, and abstraction. Provide Python examples for each.",
    type: "free_text",
    course_id: COURSES.cs101.id,
    courses: { title: COURSES.cs101.title },
    max_score: 100,
    is_mandatory: true,
    due_date: new Date(Date.now() - 1 * 86400000).toISOString(),
    answer_key: null,
    created_at: new Date(Date.now() - 8 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 8 * 86400000).toISOString(),
  },
  {
    id: "asgn-003",
    title: "Implement Binary Search",
    description: "Write a recursive binary search function in Python. Handle edge cases including empty arrays, single elements, and elements not found. Include time complexity analysis.",
    type: "code",
    course_id: COURSES.cs201.id,
    courses: { title: COURSES.cs201.title },
    max_score: 100,
    is_mandatory: true,
    due_date: new Date(Date.now() + 1 * 86400000).toISOString(),
    answer_key: null,
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: "asgn-004",
    title: "Research Paper: AI Ethics",
    description: "Upload a 2-3 page research paper discussing ethical implications of AI in education, including bias, privacy, and accessibility concerns.",
    type: "file_upload",
    course_id: COURSES.ai301.id,
    courses: { title: COURSES.ai301.title },
    max_score: 100,
    is_mandatory: true,
    due_date: new Date(Date.now() + 3 * 86400000).toISOString(),
    answer_key: null,
    created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 7 * 86400000).toISOString(),
  },
  {
    id: "asgn-005",
    title: "Machine Learning Basics Notes",
    description: "Review the provided study materials on supervised vs. unsupervised learning. Submit your notes and key takeaways.",
    type: "study_material",
    course_id: COURSES.ai301.id,
    courses: { title: COURSES.ai301.title },
    max_score: 50,
    is_mandatory: false,
    due_date: new Date(Date.now() + 5 * 86400000).toISOString(),
    answer_key: null,
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 4 * 86400000).toISOString(),
  },
];

// ── Submissions with AI Feedback (showing grading results) ──
export const demoSubmissions = [
  {
    id: "sub-001",
    assignment_id: "asgn-001",
    student_id: DEMO_USER_ID,
    content: "tuple",
    status: "graded",
    score: 85,
    submitted_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    graded_at: new Date(Date.now() - 2 * 86400000 + 30000).toISOString(),
    ai_feedback: {
      score: 85,
      feedback: "Good understanding of immutability. You correctly identified tuples as immutable sequences. However, you missed the distinction between shallow and deep immutability in nested data structures.",
      strengths: [
        "Correctly identified tuple immutability",
        "Quick response time showing confident recall",
        "Accurate understanding of basic data type properties",
      ],
      improvements: [
        "Deep vs shallow immutability in nested structures",
        "Hashability requirements for dictionary keys",
      ],
      momentum_impact: "boost",
    },
    file_url: null,
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: "sub-002",
    assignment_id: "asgn-002",
    student_id: DEMO_USER_ID,
    content: "OOP is about classes and objects. Encapsulation means hiding data. Inheritance lets you reuse code. Polymorphism is using same interface for different types.",
    status: "graded",
    score: 62,
    submitted_at: new Date(Date.now() - 1.5 * 86400000).toISOString(),
    graded_at: new Date(Date.now() - 1.5 * 86400000 + 45000).toISOString(),
    ai_feedback: {
      score: 62,
      feedback: "Your understanding of OOP is surface-level. While you correctly listed the four pillars, your explanations lack depth and concrete Python examples. The essay needs more detailed code demonstrations and real-world applications.",
      strengths: [
        "Correctly identified all four OOP pillars",
        "Clear writing structure",
      ],
      improvements: [
        "Provide concrete Python code examples for each principle",
        "Explain abstraction with real-world design patterns",
        "Demonstrate polymorphism with method overriding examples",
        "Discuss when to use composition over inheritance",
      ],
      momentum_impact: "concern",
    },
    file_url: null,
    created_at: new Date(Date.now() - 1.5 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 1.5 * 86400000).toISOString(),
  },
  {
    id: "sub-003",
    assignment_id: "asgn-003",
    student_id: DEMO_USER_ID,
    content: `def binary_search(arr, target):
    if len(arr) == 0:
        return -1
    mid = len(arr) // 2
    if arr[mid] == target:
        return mid
    elif arr[mid] < target:
        return binary_search(arr[mid+1:], target)
    else:
        return binary_search(arr[:mid], target)`,
    status: "graded",
    score: 45,
    submitted_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    graded_at: new Date(Date.now() - 1 * 86400000 + 60000).toISOString(),
    ai_feedback: {
      score: 45,
      feedback: "Your binary search has critical bugs: array slicing creates new arrays on each call (O(n) space instead of O(log n)), the index returned from recursive calls is relative to the slice, not the original array. Missing base case for single-element arrays. No time complexity analysis included.",
      strengths: [
        "Correct basic recursive structure",
        "Handles empty array edge case",
      ],
      improvements: [
        "Use low/high index parameters instead of array slicing for O(log n) space",
        "Fix index calculation — recursive return values must be adjusted for slice offset",
        "Add missing base case handling for single-element arrays",
        "Include time complexity analysis as requested in the assignment",
      ],
      momentum_impact: "concern",
    },
    file_url: null,
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: "sub-004",
    assignment_id: "asgn-004",
    student_id: DEMO_USER_ID,
    content: null,
    status: "graded",
    score: 78,
    submitted_at: new Date(Date.now() - 0.5 * 86400000).toISOString(),
    graded_at: new Date(Date.now() - 0.5 * 86400000 + 90000).toISOString(),
    ai_feedback: {
      score: 78,
      feedback: "Well-structured paper with solid coverage of bias and privacy in AI education. Your arguments are supported with relevant citations. However, the accessibility section is underdeveloped and lacks specific examples of how AI tools can be made more inclusive.",
      strengths: [
        "Strong thesis statement and logical flow",
        "Good use of recent citations (2023-2024)",
        "Thorough analysis of algorithmic bias in grading",
        "Clear writing style with professional tone",
      ],
      improvements: [
        "Expand accessibility analysis with concrete examples",
        "Discuss specific AI fairness frameworks like IBM's AI Fairness 360",
      ],
      momentum_impact: "maintain",
    },
    file_url: "demo-user/asgn-004/research-paper.pdf",
    created_at: new Date(Date.now() - 0.5 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 0.5 * 86400000).toISOString(),
  },
];

// ── Quests (Agentic + Exa-powered) ──
export const demoQuests = [
  // Active quests with Exa resource URLs
  {
    id: "quest-001",
    user_id: DEMO_USER_ID,
    title: "🔧 Fix: Variable scoping in recursive functions",
    description: 'Based on "Implement Binary Search": Use low/high index parameters instead of array slicing for O(log n) space. 📖 Resource: Learn how to properly implement recursive binary search with index-based approach — avoid common pitfalls with Python slicing.',
    type: "recovery",
    status: "active",
    xp_reward: 40,
    resource_url: "https://realpython.com/binary-search-python/",
    error_pattern: "Use low/high index parameters instead of array slicing for O(log n) space",
    generated_from: "sub-003",
    completed_at: null,
    created_at: new Date(Date.now() - 1 * 86400000 + 61000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 86400000 + 61000).toISOString(),
  },
  {
    id: "quest-002",
    user_id: DEMO_USER_ID,
    title: "📚 Rediscover: Object inheritance and design patterns",
    description: 'Based on "Explain OOP Principles": Discuss when to use composition over inheritance. 📖 Resource: A comprehensive guide to Python OOP — inheritance vs composition with practical examples.',
    type: "recovery",
    status: "active",
    xp_reward: 35,
    resource_url: "https://realpython.com/inheritance-composition-python/",
    error_pattern: "Discuss when to use composition over inheritance",
    generated_from: "sub-002",
    completed_at: null,
    created_at: new Date(Date.now() - 1.5 * 86400000 + 46000).toISOString(),
    updated_at: new Date(Date.now() - 1.5 * 86400000 + 46000).toISOString(),
  },
  {
    id: "quest-003",
    user_id: DEMO_USER_ID,
    title: "✨ Improve: Algorithm time complexity analysis",
    description: 'Based on "Implement Binary Search": Include time complexity analysis as requested. Master Big-O notation and learn to analyze recursive algorithms systematically.',
    type: "growth",
    status: "active",
    xp_reward: 25,
    resource_url: "https://www.bigocheatsheet.com/",
    error_pattern: "Include time complexity analysis as requested in the assignment",
    generated_from: "sub-003",
    completed_at: null,
    created_at: new Date(Date.now() - 1 * 86400000 + 62000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 86400000 + 62000).toISOString(),
  },
  {
    id: "quest-004",
    user_id: DEMO_USER_ID,
    title: "⚠️ Pattern Alert: Lacking concrete code examples",
    description: "You've made this same mistake across 2+ submissions. Time to master this concept! 📖 Practice writing Python code examples for every concept you explain — it reinforces understanding and demonstrates mastery.",
    type: "recovery",
    status: "active",
    xp_reward: 60,
    resource_url: "https://docs.python.org/3/tutorial/classes.html",
    error_pattern: "RECURRING: Provide concrete Python code examples for each principle",
    generated_from: "sub-002",
    completed_at: null,
    created_at: new Date(Date.now() - 1.5 * 86400000 + 47000).toISOString(),
    updated_at: new Date(Date.now() - 1.5 * 86400000 + 47000).toISOString(),
  },
  {
    id: "quest-005",
    user_id: DEMO_USER_ID,
    title: "🔧 Fix: AI fairness frameworks knowledge",
    description: 'Based on "Research Paper: AI Ethics": Discuss specific AI fairness frameworks like IBM\'s AI Fairness 360. Explore hands-on tools for detecting and mitigating bias.',
    type: "growth",
    status: "active",
    xp_reward: 30,
    resource_url: "https://aif360.mybluemix.net/",
    error_pattern: "Discuss specific AI fairness frameworks like IBM's AI Fairness 360",
    generated_from: "sub-004",
    completed_at: null,
    created_at: new Date(Date.now() - 0.5 * 86400000 + 91000).toISOString(),
    updated_at: new Date(Date.now() - 0.5 * 86400000 + 91000).toISOString(),
  },
  // Completed quests
  {
    id: "quest-006",
    user_id: DEMO_USER_ID,
    title: "✨ Improve: Python list comprehensions",
    description: "Master advanced list comprehensions with conditions, nested loops, and generator expressions.",
    type: "growth",
    status: "completed",
    xp_reward: 25,
    resource_url: "https://realpython.com/list-comprehension-python/",
    error_pattern: null,
    generated_from: null,
    completed_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 6 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 4 * 86400000).toISOString(),
  },
  {
    id: "quest-007",
    user_id: DEMO_USER_ID,
    title: "🔧 Fix: Off-by-one errors in loops",
    description: "Practice boundary conditions and loop invariants to eliminate off-by-one errors.",
    type: "recovery",
    status: "completed",
    xp_reward: 40,
    resource_url: "https://www.geeksforgeeks.org/what-is-off-by-one-error/",
    error_pattern: "Off-by-one errors in loop boundaries",
    generated_from: null,
    completed_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  // ── Side Quests (Exa-powered supplementary learning) ──
  {
    id: "sidequest-001",
    user_id: DEMO_USER_ID,
    title: "🎈 Explore: Python Decorators & Metaprogramming",
    description: "Bonus adventure! Dive into decorators, closures, and metaprogramming patterns. Broaden your Python toolkit with advanced techniques.",
    type: "sidequest",
    status: "active",
    xp_reward: 20,
    resource_url: "https://realpython.com/primer-on-python-decorators/",
    error_pattern: null,
    generated_from: null,
    completed_at: null,
    created_at: new Date(Date.now() - 0.5 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 0.5 * 86400000).toISOString(),
  },
  {
    id: "sidequest-002",
    user_id: DEMO_USER_ID,
    title: "🎈 Explore: Git Advanced Workflows",
    description: "Side quest! Master interactive rebase, cherry-pick, and bisect. Level up your version control game beyond the basics.",
    type: "sidequest",
    status: "active",
    xp_reward: 15,
    resource_url: "https://www.atlassian.com/git/tutorials/advanced-overview",
    error_pattern: null,
    generated_from: null,
    completed_at: null,
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: "sidequest-003",
    user_id: DEMO_USER_ID,
    title: "🎈 Explore: Design Patterns in Python",
    description: "Bonus knowledge! Learn Factory, Observer, and Strategy patterns with real-world Python examples. Great for writing cleaner code.",
    type: "sidequest",
    status: "active",
    xp_reward: 25,
    resource_url: "https://refactoring.guru/design-patterns/python",
    error_pattern: null,
    generated_from: null,
    completed_at: null,
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
];

// ── Agent Logs (showing the agentic decision engine) ──
export const demoAgentLogs = [
  {
    id: "log-001",
    user_id: DEMO_USER_ID,
    detected_state: "micro_stuck",
    confidence: 0.85,
    trigger_source: "submission",
    action_taken: "Generated 3 recovery quests targeting recursive function bugs and missing complexity analysis",
    reasoning: "Student scored 45% on Binary Search implementation. Detected 3 low scores in recent history and recurring pattern of missing code examples. Triggered Exa search for 'fix recursive binary search Python index error' — found Real Python tutorial. Generated targeted recovery quests.",
    patterns_found: [
      "Use low/high index parameters instead of array slicing",
      "Missing base case in recursion",
      "Provide concrete Python code examples",
    ],
    metrics_snapshot: {
      momentum: 62,
      recentAvg: 67.5,
      avgScore: 67.5,
      streak: 5,
      lowScoreCount: 3,
    },
    created_at: new Date(Date.now() - 1 * 86400000 + 61000).toISOString(),
  },
  {
    id: "log-002",
    user_id: DEMO_USER_ID,
    detected_state: "momentum_dip",
    confidence: 0.80,
    trigger_source: "submission",
    action_taken: "Generated 2 recovery quests for OOP concepts with Exa-curated resources",
    reasoning: "Student scored 62% on OOP essay. Recent score average dropped to 73.5% with a -11.5 point trend. Exa search found comprehensive Python OOP tutorials. Created quests for inheritance patterns and design principles.",
    patterns_found: [
      "Provide concrete Python code examples for each principle",
      "Discuss when to use composition over inheritance",
    ],
    metrics_snapshot: {
      momentum: 70,
      recentAvg: 73.5,
      avgScore: 73.5,
      streak: 4,
      lowScoreCount: 1,
    },
    created_at: new Date(Date.now() - 1.5 * 86400000 + 46000).toISOString(),
  },
  {
    id: "log-003",
    user_id: DEMO_USER_ID,
    detected_state: "normal",
    confidence: 0.90,
    trigger_source: "proactive_check",
    action_taken: "No intervention needed",
    reasoning: "Momentum 78%, avg score 85%, 12h since last activity. All within healthy range. Student is actively completing quests.",
    patterns_found: [],
    metrics_snapshot: {
      momentum: 78,
      recentAvg: 85,
      avgScore: 85,
      hoursSinceActivity: 12,
      staleQuests: 1,
    },
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: "log-004",
    user_id: DEMO_USER_ID,
    detected_state: "momentum_boost",
    confidence: 0.75,
    trigger_source: "proactive_check",
    action_taken: "Proactive nudge: Great streak! Keep the momentum going 🚀",
    reasoning: "Triggered momentum_boost intervention. Student showing 3 consecutive score improvements (72→78→85). Encouraged continued engagement with growth quest.",
    patterns_found: [],
    metrics_snapshot: {
      momentum: 80,
      recentAvg: 78.3,
      avgScore: 78.3,
      streak: 3,
      hoursSinceActivity: 6,
    },
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: "log-005",
    user_id: DEMO_USER_ID,
    detected_state: "skill_support",
    confidence: 0.82,
    trigger_source: "proactive_check",
    action_taken: "Proactive nudge: Your recursion skills need reinforcement — try the new quest!",
    reasoning: "Triggered skill_support intervention. Recent avg score 58% across recursion-related assignments. Exa search found beginner-friendly recursion tutorials. Generated guided practice quest.",
    patterns_found: [
      "Recursion base cases",
      "Stack frame understanding",
    ],
    metrics_snapshot: {
      momentum: 45,
      recentAvg: 58,
      avgScore: 58,
      streak: 2,
      hoursSinceActivity: 24,
      staleQuests: 4,
    },
    created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
  },
];

// ── Achievements (AI-generated with Exa resources) ──
export const demoGeneratedAchievements = [
  // Unclaimed
  {
    id: "ach-001",
    user_id: DEMO_USER_ID,
    title: "Recursion Mastery",
    description: "Complete 3 recursive algorithm challenges without bugs. Practice base cases, stack frames, and tail recursion to conquer your weakest topic.",
    emoji: "🎯",
    category: "weakness_buster",
    difficulty: "silver",
    criteria_met: null,
    resource_url: "https://realpython.com/python-recursion/",
    xp_reward: 40,
    claimed: false,
    claimed_at: null,
    generated_from: "sub-003",
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: "ach-002",
    user_id: DEMO_USER_ID,
    title: "Graph Algorithm Explorer",
    description: "Study BFS and DFS traversal algorithms. Implement at least one graph problem using adjacency lists to expand your algorithmic toolkit.",
    emoji: "🧭",
    category: "exploration",
    difficulty: "bronze",
    criteria_met: null,
    resource_url: "https://www.geeksforgeeks.org/graph-data-structure-and-algorithms/",
    xp_reward: 30,
    claimed: false,
    claimed_at: null,
    generated_from: null,
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: "ach-003",
    user_id: DEMO_USER_ID,
    title: "OOP Champion",
    description: "Demonstrate mastery of all four OOP pillars by building a mini-project using inheritance, polymorphism, encapsulation, and abstraction.",
    emoji: "💪",
    category: "strength_mastery",
    difficulty: "gold",
    criteria_met: null,
    resource_url: "https://realpython.com/python3-object-oriented-programming/",
    xp_reward: 50,
    claimed: false,
    claimed_at: null,
    generated_from: "sub-002",
    created_at: new Date(Date.now() - 1.5 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 1.5 * 86400000).toISOString(),
  },
  // Claimed
  {
    id: "ach-004",
    user_id: DEMO_USER_ID,
    title: "Consistent Coder",
    description: "Submit work for 5 consecutive days. Consistency is the key to learning momentum!",
    emoji: "📅",
    category: "consistency",
    difficulty: "bronze",
    criteria_met: "5-day submission streak achieved",
    resource_url: null,
    xp_reward: 30,
    claimed: true,
    claimed_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    generated_from: null,
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: "ach-005",
    user_id: DEMO_USER_ID,
    title: "Bounce Back",
    description: "Recover from a momentum dip by completing recovery quests and scoring above 75% on your next submission.",
    emoji: "🔄",
    category: "comeback",
    difficulty: "silver",
    criteria_met: "Recovered from 45% momentum to 78% within 48 hours",
    resource_url: null,
    xp_reward: 40,
    claimed: true,
    claimed_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    generated_from: null,
    created_at: new Date(Date.now() - 6 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
];

// ── Badge Unlocks ──
export const demoBadgeUnlocks = [
  { badge_id: "first_submit", unlocked_at: new Date(Date.now() - 25 * 86400000).toISOString() },
  { badge_id: "streak_3", unlocked_at: new Date(Date.now() - 8 * 86400000).toISOString() },
  { badge_id: "comeback", unlocked_at: new Date(Date.now() - 5 * 86400000).toISOString() },
];

// ── Study Plan (AI-generated with Exa resources) ──
export const demoStudyPlans = [
  {
    id: "plan-001",
    user_id: DEMO_USER_ID,
    title: "Week 12: Strengthening Algorithms & OOP Mastery",
    week_start: new Date(Date.now() - (new Date().getDay()) * 86400000).toISOString().split("T")[0],
    difficulty_level: "intermediate",
    status: "active",
    progress_pct: 35,
    agent_reasoning: "Analysis of your last 4 submissions reveals two key gaps: (1) recursive algorithm implementation — you're creating new arrays instead of using index-based recursion, and (2) OOP explanations lack depth. Exa search confirms these are common intermediate-level struggles. This week focuses on targeted drills with Real Python resources to build muscle memory. I've scheduled lighter topics (AI ethics review) mid-week to maintain momentum without burnout.",
    topics: [
      {
        day: "Monday",
        topic: "Recursive Binary Search — index-based approach",
        focus: "weakness",
        duration_min: 45,
        resource_url: "https://realpython.com/binary-search-python/",
        resource_title: "Real Python: Binary Search in Python",
      },
      {
        day: "Tuesday",
        topic: "OOP Deep Dive — inheritance vs composition",
        focus: "weakness",
        duration_min: 40,
        resource_url: "https://realpython.com/inheritance-composition-python/",
        resource_title: "Real Python: Inheritance and Composition",
      },
      {
        day: "Wednesday",
        topic: "AI Ethics — fairness frameworks review",
        focus: "exploration",
        duration_min: 30,
        resource_url: "https://aif360.mybluemix.net/",
        resource_title: "IBM AI Fairness 360 Toolkit",
      },
      {
        day: "Thursday",
        topic: "Big-O Analysis — recursive algorithm complexity",
        focus: "weakness",
        duration_min: 35,
        resource_url: "https://www.bigocheatsheet.com/",
        resource_title: "Big-O Cheat Sheet",
      },
      {
        day: "Friday",
        topic: "Design Patterns — apply OOP to mini-project",
        focus: "strength",
        duration_min: 50,
        resource_url: "https://refactoring.guru/design-patterns/python",
        resource_title: "Refactoring Guru: Python Design Patterns",
      },
    ],
    milestones: [
      {
        title: "Recursive Search Bug-Free",
        description: "Implement binary search with proper index tracking — no array slicing",
        xp_bonus: 30,
      },
      {
        title: "OOP Essay Revision",
        description: "Rewrite OOP essay with 4+ code examples and composition discussion",
        xp_bonus: 25,
      },
      {
        title: "Complexity Analysis Paper",
        description: "Write time/space complexity analysis for 3 recursive algorithms",
        xp_bonus: 20,
      },
    ],
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

// ── Upload page: last AI feedback for demo ──
export const demoLastFeedback = {
  score: 45,
  feedback: "Your binary search has critical bugs: array slicing creates new arrays on each call (O(n) space instead of O(log n)), the index returned from recursive calls is relative to the slice, not the original array.",
  strengths: [
    "Correct basic recursive structure",
    "Handles empty array edge case",
  ],
  improvements: [
    "Use low/high index parameters instead of array slicing for O(log n) space",
    "Fix index calculation — recursive return values must be adjusted for slice offset",
    "Add missing base case handling for single-element arrays",
    "Include time complexity analysis as requested in the assignment",
  ],
  momentum_impact: "concern",
};
